# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('manufacturer_part_num', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('date_implemented', models.DateField()),
                ('maintenance_notes', models.CharField(max_length=1000)),
                ('organization_tag', models.CharField(max_length=1000)),
            ],
        ),
    ]
